### ISSUE TITLE
Login Component

### ISSUE THREAD

**Issue by nbtdev** [nbtdev/client#1]
Each page of the NBT automation needs to have a <div> on it that serves as both a login form (when a user is not logged in) or a logout form (for when they are logged in). In other words, this form/component has two states: logged in and logged out.

The login form needs to have two fields (username and password). It should also have a Login button as well as a Clear or Reset button. In addition, it should have a "Forgot Password" link as well as a "Register" link. 

The "logout" form should display the logged-in user's callsign, plus a Logout link.

This should all be in a <div> or component element (AngularJS) that can be placed anywhere on an HTML page. This component will communicate with an API hosted on the NBT servers, for logging in and logging out a user (API TBD). 

This component should also be "theme-enabled" by using and applying particular externally-definable CSS classes (TBD).

**Comment by MaximeMorin** [comment]
1. Do you have any design or idea for your web application (client) layout? We could have a login modal "popup", a dedicated login page or a login form in the header/menu/etc.  I tend to prefer the modal popup, it would keep you on the same page.  The user wouldn't lose his context.
2. Would you prefer a [cookie based authentication or a token one](https://auth0.com/blog/2014/01/07/angularjs-authentication-with-cookies-vs-token/)?  I'm in favor of a token one, it works especially well with back-end APIs.

**Comment by nbtdev** [comment]
Hi Maxime

The goal is for a single-page interface (or as close to it as feasible -- there is a TON of functionality in the automation). 

I had done a quick mockup here: http://dev.netbattletech.com that may explain the idea I have in mind for this component. The login component would be able to live anywhere on the page (upper right in this case). 

The access will be token-based. The API (at its current level of limited functionality) is up and running at api-dev.netbattletech.com (still working on initial documentation, but you can get the idea if you chase the links returned). One of the URLs in the API provides a token based on login credentials, and that token would need to be passed in an X-NBT-Token header with each call (once obtained). The login component could encapsulate this token and make it available to other parts of the page on demand (preferably a getter function).

**Comment by MaximeMorin** [comment]
@nbtdev Any progress on the documentation for the authentication and registration APIs?

Is it possible to have your mockup back?  For some reason dev and dev-api returns the exact same JSON result.

**Comment by nbtdev** [comment]
Hi Maxime

On documentation, I confess that I started and got sidetracked and never got back to it; I have an idea how I want to approach it and will work on that this evening.

In the meantime, I did get the dev API going with the latest code; most of the changes are for planet/faction/battle access, so the login features should be the same. 

There is one login in the system, that has no access to anything, that is available to test with:

username: testuser
password: testpass

Using this data should return an active token (that doesn't have any real permissions).

**Comment by nbtdev** [comment]
Also, a couple of design notes to consider while docs are being assembled:
- The intent is for any API request that is not accompanied by a valid, non-expired token, the response will include "login" and "register" links. For all other requests, the response will include "logout" links. 
- Any link with POST or PUT method, will be accompanied by an additional link to a template for the data that method expects (object template, in other words), and this template includes the field name, data type, and suggested "prompt" text

The dev API does not fully implement the first bullet at this time, but I'll fix that up for the existing set of resources today, and apps can expect this to be the case going forward.

Thanks!

**Comment by nbtdev** [comment]
OK, http://api-dev.netbattletech.com has the login/signup/logout links for all current URLs (except those under /system), and which ones are there, are determined by presence/absence of a valid token in X-NBT-Token header.

I will keep working on docs for the "hypermedia" types, let me know if you have questions in the meantime. I am also actively on NBT TS3 in evenings PST (GMT-7).

**Comment by MaximeMorin** [comment]
Thanks for all the information, I've successfully connected via the API with the test user.  I'm going to be working on injecting the token and logout next.

**Comment by MaximeMorin** [comment]
@nbtdev Do you have the URL and method for the logout?  This will enable me to check if my token injection works correctly.

**Comment by nbtdev** [comment]
Ah, good point -- I checked all of the URL responses except for the one at /security/tokens. ;) I will add the logout link there too, but it currently is just /security/tokens/{token}, DELETE method.

**Comment by MaximeMorin** [comment]
@nbtdev I like that the URL is the same as the login with a different verb, but do you really need the token parameter?  It will be available via the X-NBT-Token header.

**Comment by robertwtucker** [comment]
Functionally, probably not. From a semantic perspective, though, it is important as it eliminates any ambiguity as to what the target of the request is.

**Comment by nbtdev** [comment]
Yes, in terms of REST correctness, the full URL is the proper way to handle that. The token header is not actually needed in that request, but it's harmless if supplied (it's ignored in the handler for that URL).

**Comment by MaximeMorin** [comment]
@robertwtucker That's a good point!

**Comment by nbtdev** [comment]
Hi Maxime

Are you still working on this? Just want to know if I should go ahead and implement it or not.

Thanks!

**Comment by MaximeMorin** [comment]
Not really, sorry.  Feel free to take a look at what I did back then.
https://github.com/MaximeMorin/nbt-client  (app folder)

**Comment by nbtdev** [comment]
No worries, just wanted to check to make sure I wasn't stepping on any toes. Thanks!

**Comment by nbtdev** [comment]
Closed as completed as of afa660939d58ddec4112290bb856d6217c54da60
