### ISSUE TITLE
Can overload dropship when loading units from planet

### ISSUE THREAD

**Issue by nbtdev** [nbtdev/client#137]

**Comment by billyblackerby** [comment]
I was able to do this when loading up after the fight on Wyatt. I went into -1 capacity on the drop ship. I initially tried to load too much, and got an error. Then I tried again with a smaller set, and was able to overload with a multi-select.

**Comment by nbtdev** [comment]
Finally figured this out and fixed it. Turns out it was related to the type hierarchy (dropships have different capacities for different types of combat units). While we only have one base type in MWO, they are still divided into at least two subtypes -- Clan Mechs and IS Mechs. The code that ensured the dropship had sufficient capacity, was checking the subtype (Clan/IS Mech) against the main type (Battlemech) capacity, so when you would load, say, 10 IS and 40 Clan mechs onto an empty Clan Overlord-C (capacity: 45 Battlemech) it would OK it because both 10 and 40 are less than 45. The code would work when all of the mechs were a single type (for instance, trying to load 50 Clan or IS mechs onto any Overlord would properly fail).
